name: Feature Request
description: Looking for a feature
title: "[Feature] "
labels: ["enhancement"]
projects: [Development-Corps/2] # Auto-magically tie to the org overview project
assignees:
  - Development-Corps/core-developer 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form. Please include as much detail as possible!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: Give us the details.
      description: What would make the product better?
      placeholder: Details...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Development-Corps/.github?tab=coc-ov-file#readme).
