name: Discussion
description: For open-ended discussions or brainstorming, please visit our Discord or GitHub Discussions board.
title: "[DISCUSSION] "
labels: [invalid]
projects: [Development-Corps/2] # Auto-magically tie to the org overview project
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Discussions and Brainstorming

        For open-ended discussions or brainstorming sessions, we encourage you to use our [Discord server (this is a WIP)](#) or our [GitHub Discussions board](https://github.com/orgs/Development-Corps/discussions).

        This helps keep our issues focused on actionable tasks and bug reports.

        Thank you for your understanding and participation!

  - type: textarea
    attributes:
      label: Don't Write Here Please!
      description: GitHub requires a non-markdown block here.
      placeholder: |
        GitHub requires a non-markdown block, so this is here.
        That said, please read above as this is an issue that will most likely be funneled into the discussions section anyway!
