blank_issues_enabled: false
contact_links:
  - name: Development Corps Community
    url: https://github.com/orgs/Development-Corps/discussions
    about: Development Corps commnity discussions page.
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: General GitHub community support.
  # - name: GitHub Security Bug Bounty
  #   url: https://bounty.github.com/
  #   about: Please report security vulnerabilities here.